name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build the stack
      run: docker-compose -f docker-compose-tests.yml up -d
    - name: Build
      run: go build -v github.com/gicappa/interview-accountapi/cmd/client_example
    - name: Test
      run: go test -v ./...
